### ISSUE TITLE
Implement missing abilities

### ISSUE THREAD

**Issue by GitWither** [GitWither/Elemental-Forces#18]
**THIS LIST IS NOT FINISHED AND WILL CHANGE!**

**Air:**
1. ~Tornado using mob AI~
2. ~Put a cloud beneath you, can be used for double jump.~

**Rock:**
1. ~Blow up players with TNT~
2. ~Invulnerability in rock~

**Ice:**
1. ~Freeze other players in an area~
2. ~Speed on ice path~

**Fire:**
1. ~Flame trail where you walk~
2. ~Jetpack/rocket boost in the air~

**Nature:**
1. ~Area with cacti that deal damage~
2. No idea

**Undead:**
1. ~Summon skeletons~
2. Teleport back a few seconds

**Comment by PingiPuck** [comment]
YEAYAYYAYAYYAYAAAAAEH FINALLY OHHH SHIT

**Comment by GitWither** [comment]
this is a Christian repository please no swearing also pls edit the description to match the reality @PingiPuck
